name: build

on:
  push:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.xaml'
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.xaml'

env:
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use

jobs:
  build:

    name: Build All Projects
    runs-on: windows-latest
        
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      with:
        vs-prerelease: true
    
    - name: Install .NET workloads
      shell: pwsh
      run: |
        dotnet workload install android
        dotnet workload install ios
        dotnet workload install maccatalyst
        dotnet workload install maui
      
    - name: Build .NET MAUI Conference App
      run: dotnet build src/Conference.Maui/Conference.Maui.csproj